version: '3'

services:
  backend-app:
    depends_on:
      - db
    container_name: backend-app
    image: backendapp:1.0.0
    build:
      context: .
      #dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
     - .env
    environment:
      - MONGODB_URI: $MONGODB_URI
      - OPEN_WEATHER_API_KEY: $OPEN_WEATHER_API_KEY

  # Database service
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: 